name: help
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  country_picker: ^2.0.18
  firebase_core: ^2.8.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.6
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  pinput: ^2.2.16
  image_picker: ^0.8.6




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:


  uses-material-design: true
  assets:
    - assets/